# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Journeyman's Travels
subtitle:
# description: The blog of a journeyman software engineer.
keywords: software, engineer, journeyman, scheufler, consultant
author: Daniel Scheufler
language: en
timezone: America/Chicago

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://daniel.scheufler.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

sitemap:
  path: sitemap.xml

# Category & Tag
default_category: Software Development
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: Daily
theme: DJS
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: github.com/djscheuf/journeymans-blog

#Custom Setting Start

feed:
  type: rss2
  path: rss2.xml
  limit: 10

# Site settings
SEOTitle: Journeyman's Travels
email: daniel@shceufler.io
google_analytics: UA-86343000-1

# Social Links
social:
  github: https://github.com/djscheuf
  mail: mailto:daniel@scheufler.io
  linkedin: https://www.linkedin.com/in/danielscheufler/
  rss: /rss2.xml

# Navigation Bar
nav:
  Home: .
  Now: now
  User's Manual: manual
  About: about
  Archive: archives

widget:
  title: A Journeyman's Travels
  content: <span>Blog by <a href="/about">Daniel Scheufler</a>.</span>

# Visual Config
# avatar: img/better_me_sm.png
# banner_small: images/banner-small.png
# banner_large: img/header_img/home-bg-2-dark.png
logo: /img/logo/star_catcher_mountains.png
favicon: /img/logo/star_catcher_mountainsx96.png

featured:
  active: true
  articles:
    - id: 0
      title: Code is read more often than it is written
      link: /2016/12/27/Code-is-read-more-often-than-it-is-written/
    - id: 1
      title: Models are not Reality
      link: /2019/12/09/models-are-not-reality/
    - id: 2
      title: Mere Exposure
      link: /2019/11/18/mere-exposure/
    - id: 3
      title: An Angular Preview Mode
      link: /2020/01/06/angular-preview-mode/
    - id: 4
      title: Dungeons and Dragons and Leadership Training?
      link: /2017/02/07/Dungeons-and-Dragons-and-Leadership-Training/
    - id: 5
      title: Opportunity in Crisis
      link: /2020/03/30/oppurtunity-in-crisis/
    - id: 6
      title: The 2 Minute Rule
      link: /2020/02/17/two-minute-rule/
    - id: 7
      title: A Developer's Best Friend
      link: /2019/02/11/a-developers-best-friend/
    - id: 8
      title: Models are not Reality
      link: /2019/12/09/models-are-not-reality/
    - id: 9
      title: Just enough here to make something wonderful
      link: /2020/01/13/just-enough-here-to-make-something/
